FROM python:3.12-slim

WORKDIR /app

RUN pip install uv

COPY shenbid/uv.lock shenbid/pyproject.toml ./
RUN uv export --frozen --no-dev --no-hashes -o requirements.txt && \
    uv pip install --system -r requirements.txt

COPY shenbid/app ./app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
